"""
Django settings for sitotest project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)#
#----------------------------------------------------------------------#
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#----------------------------------------------------------------------#


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&fq6lssp5b25s$+j=q$^^v95fw7n_gup3pbi*h#8ea!e1*to7x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []







         # Configurazioni smtp #
#----------------------------------------------#
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'espositogerardo94@gmail.com'
EMAIL_HOST_PASSWORD = '0806040200'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#----------------------------------------------#

# Configurazioni invio mail di conferma iscrizione #
#--------------------------------------------------#
def verified_callback(user):
    user.is_active = True


EMAIL_VERIFIED_CALLBACK = verified_callback
EMAIL_FROM_ADDRESS = 'espositogerardo94@gmail.com'
EMAIL_MAIL_SUBJECT = 'Confirm your email'
EMAIL_MAIL_HTML = 'mail_body.html'
EMAIL_MAIL_PLAIN = 'mail_body.txt'
EMAIL_TOKEN_LIFE = 60 * 60
EMAIL_PAGE_TEMPLATE = 'confirm_template.html'
EMAIL_PAGE_DOMAIN = 'http://mydomain.com/'




#-------------------------------------------------#



####SITEMAP####
SITE_ID=1
#-------------#

                        # Definizione Applicazioni del sito #
#------------------------------------------------------------------------------------------#
INSTALLED_APPS = [
    'adminactions',
    'captcha',
    'landing_page',
    'taggit',
    'rest_framework',
    'colorful',
    'login.apps.LoginConfig',
    'jet.dashboard',
    'jet',
    'django_email_verification', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
]
#-------------------------------------------------------------------------------------------#

REST_FRAMEWORK = {
	'DEFAULT_PERMISSION_CLASSES': [
		    'rest_framework.permissions.IsAuthenticated',
		]
	}
#-------------------------------------------------------------------------------------------#
                             # Temi Sito e configurazioni middleware jet #
#-------------------------------------------------------------------------------------------#
JET_THEMES = [
    {
        'theme': 'default', # theme folder name
        'color': '#47bac1', # color of the theme's button in user menu
        'title': 'Default' # theme title
    },
    {
        'theme': 'green',
        'color': '#44b78b',
        'title': 'Green'
    },
    {
        'theme': 'light-green',
        'color': '#2faa60',
        'title': 'Light Green'
    },
    {
        'theme': 'light-violet',
        'color': '#a464c4',
        'title': 'Light Violet'
    },
    {
        'theme': 'light-blue',
        'color': '#5EADDE',
        'title': 'Light Blue'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light Gray'
    }
]

JET_SIDE_MENU_COMPACT = True
JET_CHANGE_FROM_SIBILIG_LINKS = True 
JET_INDEX_DASHBOARD = 'jet.dashboard.dashboard.DefaultIndexDashboard'
#-------------------------------------------------------------------------------------------#
                                # Repo per middleware #
#-------------------------------------------------------------------------------------------#
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#--------------------------------------------------------------------------------------------#

	 # Withelist per CORS #
#---------------------------------#
#CORS_ORIGIN_WHITELIST = (
#	'http://localhost:3000',
#	'http://localhost:8000',
#	'http://localhost:6379',
#	)
#---------------------------------#



ROOT_URLCONF = 'sitotest.urls'

                             # impostazioni template #
#--------------------------------------------------------------------------------------------#
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'landing_page', 'templates', 'landing_page')
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#--------------------------------------------------------------------------------------------#










             # Impostazioni per la scelta del Database #
  # https://docs.djangoproject.com/en/3.0/ref/settings/#databases #
#-------------------------------------------------------------------#
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
#-------------------------------------------------------------------#








                 # Validazione delle password di autenticazione #
      # https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators #
#-------------------------------------------------------------------------------------------#
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
#-------------------------------------------------------------------------------------------#





              # Internationalization #
# https://docs.djangoproject.com/en/3.0/topics/i18n/#
#---------------------------------------------------#
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
#---------------------------------------------------#





        # Static files (CSS, JavaScript, Images) #
# https://docs.djangoproject.com/en/3.0/howto/static-files/ #
#-----------------------------------------------------------#
STATIC_URL = '/static/landing_page/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, '/static/landing_page/'),
)
#-----------------------------------------------------------#


                  # Image files #
#-----------------------------------------------------------#
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
#-----------------------------------------------------------#


# Pagine di redirect post Login/Logout #
#--------------------------------------#
LOGIN_REDIRECT_URL = '/landing_page/'
LOGOUT_REDIRECT_URL = '/landing_page/'
#--------------------------------------#





                    #CHANNEL_LAYERS#
#------------------------------------------------------------#
ASGI_APPLICATION = 'routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
#------------------------------------------------------------#
