# Generated by Django 3.0.8 on 2020-10-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('corpo', models.TextField()),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
                ('attivo', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='landing_page.Post')),
            ],
            options={
                'ordering': ('creato',),
            },
        ),
    ]
