# Generated by Django 3.0.8 on 2020-10-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_commenti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenti',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='landing_page.Post'),
        ),
    ]
