# Generated by Django 3.1.5 on 2021-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_auto_20210112_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/%y/%m/%d'),
        ),
    ]
