# Generated by Django 2.2.16 on 2021-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0009_slider_1_slider_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider_1',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slider_2',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slider_1',
            name='descrizione_prima_slide',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slider_1',
            name='descrizione_seconda_slide',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slider_1',
            name='descrizione_terza_slide',
            field=models.TextField(blank=True),
        ),
    ]
