# Generated by Django 2.2.16 on 2021-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0010_auto_20210309_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, upload_to='home-gallery/1')),
                ('img2', models.ImageField(blank=True, upload_to='home-gallery/2')),
                ('img3', models.ImageField(blank=True, upload_to='home-gallery/3')),
                ('img4', models.ImageField(blank=True, upload_to='home-gallery/4')),
                ('img5', models.ImageField(blank=True, upload_to='home-gallery/5')),
                ('img6', models.ImageField(blank=True, upload_to='home-gallery/6')),
                ('img7', models.ImageField(blank=True, upload_to='home-gallery/7')),
                ('img8', models.ImageField(blank=True, upload_to='home-gallery/8')),
                ('img9', models.ImageField(blank=True, upload_to='home-gallery/9')),
                ('img10', models.ImageField(blank=True, upload_to='home-gallery/10')),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='IPAddr',
        ),
    ]
