# Generated by Django 2.2.16 on 2021-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0014_titoli_landing_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='content_chisiamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titoli', models.CharField(max_length=100)),
                ('contenuto', models.TextField()),
                ('current', models.BooleanField(default=False)),
            ],
        ),
    ]
