# Generated by Django 2.2.16 on 2021-03-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0015_content_chisiamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='content_mappa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('sottotitolo', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current', models.BooleanField(default=False)),
                ('api_key_mappa', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='content_chisiamo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='titoli_landing_page',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='titoli_landing_page',
            name='scritta_centrale_pagina',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='titoli_landing_page',
            name='titolo_catalogo_prodotti',
            field=models.CharField(max_length=50),
        ),
    ]
