# Generated by Django 2.2.16 on 2021-03-29 08:36

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0017_content_mappa_api_key_captcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scelta_ruolo', models.CharField(choices=[('1', 'INFORMATICO'), ('2', 'MECCANICO'), ('3', 'SALDATORE'), ('4', 'ELETTRICISTA')], default='1', max_length=10)),
                ('esperienza', models.CharField(choices=[('1', 'nessuna esperienza'), ('2', 'meno di un anno'), ('3', '1 anno o più')], default='1', max_length=10)),
                ('nome_candidato', models.CharField(max_length=120)),
                ('cognome_candidato', models.CharField(max_length=120)),
                ('indirizzo_candidato', models.CharField(max_length=120)),
                ('email_candidato', models.EmailField(max_length=254)),
                ('cellulare_candidato', models.CharField(max_length=10)),
                ('cv', models.FileField(upload_to='candidati/curricula/cv_%y%m%d')),
            ],
        ),
        migrations.AddField(
            model_name='titoli_landing_page',
            name='colore_scritta_centrale',
            field=colorful.fields.RGBColorField(default='black'),
        ),
        migrations.AddField(
            model_name='titoli_landing_page',
            name='colore_titolo_catalogo',
            field=colorful.fields.RGBColorField(default='blue'),
        ),
    ]
