# Generated by Django 3.1.7 on 2021-03-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0018_auto_20210329_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='esperienza',
            field=models.CharField(choices=[('1', 'nessuna esperienza'), ('2', 'meno di un anno'), ('3', '1 anno o più')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='scelta_ruolo',
            field=models.CharField(choices=[('1', 'INFORMATICO'), ('2', 'MECCANICO'), ('3', 'SALDATORE'), ('4', 'ELETTRICISTA')], default='1', max_length=1),
        ),
    ]
