# Generated by Django 3.1.7 on 2021-04-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0019_auto_20210329_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='link_footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefonico_1', models.CharField(max_length=10)),
                ('numero_telefonico_2', models.CharField(max_length=10)),
                ('indirizzo_mail', models.EmailField(max_length=254)),
                ('partita_IVA', models.CharField(max_length=11)),
                ('titolo_link_1', models.CharField(max_length=20)),
                ('titolo_link_2', models.CharField(max_length=20)),
                ('titolo_link_3', models.CharField(max_length=20)),
                ('link_1', models.CharField(max_length=100)),
                ('link_2', models.CharField(max_length=100)),
                ('link_3', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='Logo/%y%m%d')),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='slider_2',
            name='image_prima_slide',
            field=models.ImageField(blank=True, upload_to='img-slider-2/1'),
        ),
        migrations.AlterField(
            model_name='slider_2',
            name='image_seconda_slide',
            field=models.ImageField(blank=True, upload_to='img-slider-2/2'),
        ),
        migrations.AlterField(
            model_name='slider_2',
            name='image_terza_slide',
            field=models.ImageField(blank=True, upload_to='img-slider-2/3'),
        ),
    ]
