# Generated by Django 3.1.7 on 2021-04-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0020_auto_20210408_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_lavora_con_noi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(blank=True, upload_to='Banner_chisiamo/%y%m%d')),
                ('titolo_banner', models.CharField(max_length=50)),
                ('sottotitolo_banner', models.CharField(max_length=100)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='content_lavora_con_noi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_paragrafo_1', models.CharField(max_length=20)),
                ('titolo_paragrafo_2', models.CharField(max_length=20)),
                ('paragrafo_1', models.TextField()),
                ('paragrafo_2', models.TextField()),
                ('current', models.BooleanField(default=False)),
            ],
        ),
    ]
