# Generated by Django 3.1.7 on 2021-04-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0021_banner_lavora_con_noi_content_lavora_con_noi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_lavora_con_noi',
            name='titolo_paragrafo_1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='content_lavora_con_noi',
            name='titolo_paragrafo_2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='link_footer',
            name='titolo_link_1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='link_footer',
            name='titolo_link_2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='link_footer',
            name='titolo_link_3',
            field=models.CharField(max_length=30),
        ),
    ]
