# Generated by Django 3.1.7 on 2021-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0025_certificati'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='hero/%y%m%d')),
                ('titolo_header', models.CharField(blank=True, default='EMMEGÌ2000', max_length=150)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
    ]
