# Generated by Django 3.1.7 on 2021-04-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0026_img_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img_hero',
            options={'verbose_name': 'header', 'verbose_name_plural': 'headers'},
        ),
    ]
