# Generated by Django 3.1.7 on 2021-04-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0027_auto_20210421_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner_lavora_con_noi',
            options={'verbose_name': "banner pagina 'lavora con noi", 'verbose_name_plural': "banner pagina 'lavora con noi"},
        ),
        migrations.AlterModelOptions(
            name='candidato',
            options={'verbose_name': 'candidato per assunzioni', 'verbose_name_plural': 'candidati per assunzione'},
        ),
        migrations.AlterModelOptions(
            name='certificati',
            options={'verbose_name': 'certificato', 'verbose_name_plural': 'certificati'},
        ),
        migrations.AlterModelOptions(
            name='content_chisiamo',
            options={'verbose_name': "contenuti pagina 'Chi Siamo'", 'verbose_name_plural': "contenuti pagina 'Chi Siamo'"},
        ),
        migrations.AlterModelOptions(
            name='content_lavora_con_noi',
            options={'verbose_name': "contenuti pagina 'lavora con noi'", 'verbose_name_plural': "contenuti pagina 'lavora con noi'"},
        ),
        migrations.AlterModelOptions(
            name='content_mappa',
            options={'verbose_name': "contenuti pagina 'Mappa' e api key Captcha", 'verbose_name_plural': "contenuti pagina 'Mappa' e api key Captcha"},
        ),
        migrations.AlterModelOptions(
            name='home_gallery',
            options={'verbose_name': 'galleria home', 'verbose_name_plural': 'gallerie home'},
        ),
        migrations.AlterModelOptions(
            name='link_footer',
            options={'verbose_name': 'gestione footer', 'verbose_name_plural': 'gestione footer'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'prodotto', 'verbose_name_plural': 'prodotti'},
        ),
        migrations.AlterModelOptions(
            name='servizi',
            options={'verbose_name': 'servizio', 'verbose_name_plural': 'servizi'},
        ),
        migrations.AlterModelOptions(
            name='slider_1',
            options={'verbose_name': 'primo slider', 'verbose_name_plural': 'primo slider'},
        ),
        migrations.AlterModelOptions(
            name='slider_2',
            options={'verbose_name': 'secondo slider', 'verbose_name_plural': 'secondo slider'},
        ),
        migrations.AlterModelOptions(
            name='titoli_landing_page',
            options={'verbose_name': 'titoli su landing page', 'verbose_name_plural': 'titoli su landing page'},
        ),
    ]
